#!/bin/sh

sed -i '/insert preincludes/a #include "ast_main.cpp"' Parserbase.h;

sed -i '\|STYPE__     d_val__;| d 
' Parserbase.h

sed -i '\|typedef Meta__::SType STYPE__;|a \\tpublic: static STYPE__  d_val__;
' Parserbase.h 



#Observe how the delimiter was changed from / to |
#-i for inplace update
# d for delete
# a for append (or insert)