#!/bin/sh

sed -i '/include/a #include "Parserbase.h"' Scanner.ih;
sed -i '/insert preincludes/a #include "ast_main.cpp"' Parserbase.h;
sed -i '/insert preincludes/a #include "symbol_table.cpp"' Parserbase.h;
sed -i '/include "Parser.h"/a #include "st_helper.cpp"' Parser.ih;

sed -i '\|STYPE__     d_val__;| d 
' Parserbase.h

sed -i '\|typedef Meta__::SType STYPE__;| a \\tpublic: static STYPE__  d_val__;\nstatic int lineCount;
' Parserbase.h 

sed -i '\|void Parser::print__()| i Meta__::SType ParserBase::d_val__;\nint ParserBase::lineCount=1;
' parse.cc

#Observe how the delimiter was changed from / to |
#-i for inplace update
# d for delete
# a for append (or insert)